sudo: required
services:
  - docker

before_install:
  - docker build -t williamhgough/docker-react -f Dockerfile.dev .

script:
  - docker run williamhgough/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-788284620647"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_ACCESS_SECRET
